export const MISSIONS_REQUEST_START = 'MISSIONS_REQUEST_LOADING';
export const MISSIONS_REQUEST_DONE = 'MISSIONS_REQUEST_DONE';
export const MISSIONS_REQUEST_ERROR = 'MISSIONS_REQUEST_ERROR';
export const LOADING_ROCKET_REQUEST = 'LOADING_ROCKET_REQUEST';
export const GET_CURRENT_ROCKETS_SUCCESS = 'GET_CURRENT_ROCKETS_SUCCESS';
export const ROCKET_REQUEST_FAILURE = 'ROCKET_REQUEST_FAILURE';
export const CHANGE_RESERVATION = 'CHANGE_RESERVATION';
export const JOIN_MISSION = 'JOIN_MESSION';
