export const LOADING_ROCKET_REQUEST = 'LOADING_ROCKET_REQUEST';
export const GET_CURRENT_ROCKETS_SUCCESS = 'GET_CURRENT_ROCKETS_SUCCESS';
export const ROCKET_REQUEST_FAILURE = 'ROCKET_REQUEST_FAILURE';
export const CHANGE_RESERVATION = 'CHANGE_RESERVATION';
